### ISSUE TITLE
Should have option for clean profile

### ISSUE THREAD

**Issue by ecki** [nccgroup/Wubes#2]
Right now if you dont provide the content of your  desktop profile Firefox will fail and you have to manually delete the %APPDATA%\Mozilla\Firefox\profiles.ini file.

I think copying the profile data into the sandbox might often be a quite bad idea, so it should offer the option to run with an empty profile - for example if the source folder was not populated.

**Comment by saidelike** [comment]
Good idea. Done.

Can you detail why you think copying the profile data into the sandbox might often be quite a bad idea?

**Comment by ecki** [comment]
I was thinking if you want to use the sandbox for browsing with more privacy or on risky sites you don’t want to have bookmarks, history, formfields or passwords available to an attacker. (This would be a use case to not do the trusted browsing in that sandbox)
